version: '3'

services:

  rpl0:
    image: mongo:4.4
    ports:
      - "30000:30000"
    command: mongod --replSet myrplset
    volumes:
      - rpl0_data:/data/db
      - ./nmbprsdata0:/nmbpdata

  rpl1:
    image: mongo:4.4
    ports:
      - "30001:30001"
    command: mongod --replSet myrplset
    volumes:
      - rpl1_data:/data/db
      - ./nmbprsdata1:/nmbpdata

  rpl2:
    image: mongo:4.4
    ports:
      - "30002:30002"
    command: mongod --replSet myrplset
    volumes:
      - rpl2_data:/data/db
      - ./nmbprsdata2:/nmbpdata

  rpl3:
    image: mongo:4.4
    ports:
      - "30003:30003"
    command: mongod --replSet myrplset
    volumes:
      - rpl3_data:/data/db
      - ./nmbprsdata3:/nmbpdata

    
  rpl4:
    image: mongo:4.4
    ports:
      - "30004:30004"
    command: mongod --replSet myrplset
    volumes:
      - rpl4_data:/data/db
      - ./nmbprsdata4:/nmbpdata

volumes:
  rpl0_data:
  rpl1_data:
  rpl2_data:
  rpl3_data:
  rpl4_data:
